# a game about picking up apples :)
# (its not so simple)
import time as t

print(
    """
Welcome to this little game about picking apples :)
Let's see whether you'll live to see yet another day^^
All you gotta do is decide between the following four options:

You can 'pick' an apple
You can also type 'skip' if you do not wish to pick an apple
With 'eat' you can, well, eat an apple
You can 'drop' your apples if you want to
And most importantly, you can 'deliver' your apples.

Doesn't sound too difficult does it? :D
Good luck!"""
)

t1 = t.time()


options = "(pick/skip/eat/drop/deliver)"
message = f"So watcha wanna do next? {options} - "
timelim = 300
nrturns = 0
turnslim = 60
nextdelivery = 0
deliveries = [
    {"nr": 4, "dis": 4}, {"nr": 3, "dis": 5},
    {"nr": 7, "dis": 3}, {"nr": 2, "dis": 9}
]
nrapples = 0
carrylim = 10
hunger = 0
hungerlim = 5
eaten = 0
eatlim = 7
motivation = 0
# the bigger the less motivation
motlim = 7
skips = 0
skipslim = 3
delfactor = 5
# factor by which effort of deliveries is divided by. the bigger, the less
# hunger is generated by making a delivery

poisonous = [
    "0", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1",
    "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1", "0", "0", "0",
    "0", "0", "1", "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1",
    "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1", "0", "0", "0",
    "0", "0", "1", "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1",
    "0", "0", "0", "0", "0", "1", "0", "0", "0", "0", "0", "1", "0", "0", "0"
]


def kill():
    pass


def gameover():
    pass


def pick():
    global nrturns, nrapples, hunger, motivation, skips
    t.sleep(1)
    if poisonous[nrturns] == "1":
        nrturns += 1
        print("""
While trying to pick the apple, something bit you in the hand.
it hurts but you just leave that apple alone and continue
""")
        inputt = input(message)
        do(inputt)
        print("""
You notice that you begin to sweat strongly for no obvious reason""")
        t.sleep(2)
        print("""
Also your mouth starts tingling and you start twitching in the face""")
        t.sleep(2)
        print("""
Nonetheless, you continue
""")
        inputt = input(message)
        do(inputt)
        print("""
Suddenly you need to vomit and you've now got severe muscle spasms""")
        t.sleep(3)
        print("""
You feel slowly loosing consciousness...""")
        t.sleep(2)
        print("\
                             and never wake again...\
")
        gameover()
    else:
        nrturns += 1
        nrapples += 1
        hunger += 0.4
        motivation += 1
        skips = 0
        kill()


def skip():
    global nrturns, hunger, motivation, skips
    t.sleep(1)
    nrturns += 1
    hunger += 0.2
    motivation -= 1
    skips += 1
    kill()


def eat():
    global nrturns, nrapples, hunger, eaten, motivation, skips
    t.sleep(1)
    if nrapples >= 1:
        nrturns += 1
        nrapples -= 1
        hunger = 0
        eaten += 1
        skips += 0.5
        motivation -= 2
        kill()
    else:
        nrturns += 1
        motivation += 2
        print("""Having tried to eat an apple without even having one in your
basket at the moment, you think strongly about your stupidity.""")
        kill()
        print("""In spite of feeling a deep disappointment in yourself, you decide
not to kill yourself this time.""")


def drop():
    global nrturns, nrapples, motivation, skips
    t.sleep(1)
    nrturns += 1
    nrapples = 0
    motivation += 2
    skips += 1
    kill()


def deliver():
    global nrturns, nrapples, hunger, motivation, skips, nextdelivery
    t.sleep(deliveries[nextdelivery]["dis"])
    skips = 0
    nrturns += 1
    journthere = deliveries[nextdelivery]["dis"] * nrapples / delfactor
    hunger += journthere
    kill()
    nrapples -= deliveries[nextdelivery]["nr"]
    kill()
    t.sleep(deliveries[nextdelivery]["dis"])
    motivation = 0
    journback = deliveries[nextdelivery]["dis"] * nrapples / delfactor
    hunger += journback
    kill()
    nextdelivery += 1


def do(pinput):
    pinput == pinput.lower()
    if pinput == "pick":
        pick()
    elif pinput == "skip":
        skip()
    elif pinput == "deliver":
        deliver()
    elif pinput == "drop":
        drop()
    elif pinput == "eat":
        eat()
    else:
        print("Please repeat that...")


def dodo():
    inputt = input(message)
    do(inputt)
    print(
        f"nrturns {nrturns}   ",
        f"nextdelivery {nextdelivery}   ",
        f"nrapples {nrapples}   ",
        f"hunger {hunger}   ",
        f"eaten {eaten}   ",
        f"motivation {motivation}   ",
        f"skips {skips}   "
    )


while t.time() - t1 < timelim:
    dodo()

print("ran outta time boy")
